/-
Copyright 2026 The Formal Conjectures Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-/

import FormalConjectures.Util.ProblemImports

/-!
# Subword complexity of the morphism a → aab, b → b

Let $a_n$ be the number of distinct subwords (contiguous factors) of length $n$ in the infinite
word generated by the morphism $\sigma: a \mapsto aab, b \mapsto b$, starting from $a$.

The conjectured generating function is:
$$\sum_{n \geq 0} a_n x^n = 1 + \frac{1}{1-x} + \frac{1}{(1-x)^2}\left(\frac{1}{1-x} -
  \sum_{k \geq 1} x^{2^k + k - 1}\right).$$

*References:*
- [OEIS A006697](https://oeis.org/A006697)
- J.-P. Allouche and J. Shallit, "On the subword complexity of the fixed point of a → aab, b → b,
  and generalizations," arXiv:1605.02361 [math.CO], 2016.
- N. J. A. Sloane and Simon Plouffe, *The Encyclopedia of Integer Sequences*, Academic Press, 1995.
-/

namespace OEIS.A006697

open PowerSeries

/-- The morphism σ on {a, b} defined by a ↦ aab, b ↦ b, represented on Bool where
`false` = a and `true` = b. -/
def morphism : Bool → List Bool
  | false => [false, false, true]  -- a ↦ aab
  | true => [true]                  -- b ↦ b

/-- Apply the morphism to a list of symbols. -/
def applyMorphism (w : List Bool) : List Bool :=
  w.flatMap morphism

/-- The n-th iterate of the morphism applied to [a]. -/
def iterateMorphism : ℕ → List Bool
  | 0 => [false]
  | n + 1 => applyMorphism (iterateMorphism n)

/-- The infinite word w is the fixed point of the morphism starting from 'a'.
We define it as the limit: w(i) is the i-th symbol, which stabilizes after
sufficiently many iterations. -/
noncomputable def infiniteWord (i : ℕ) : Bool :=
  (iterateMorphism (i + 1)).getD i false

/-- A subword (factor) of length n starting at position i. -/
noncomputable def subwordAt (i n : ℕ) : List Bool :=
  (List.range n).map fun j => infiniteWord (i + j)

/-- The set of all distinct subwords of length n in the infinite word. -/
def subwordsOfLength (n : ℕ) : Set (List Bool) :=
  {w | ∃ i, w = subwordAt i n}

/-- The subword complexity function: a(n) is the number of distinct subwords of length n. -/
noncomputable def a (n : ℕ) : ℕ := (subwordsOfLength n).ncard

/-- The conjectured generating function for the subword complexity. -/
noncomputable def generatingFunction : PowerSeries ℚ :=
  1 + (1 - X)⁻¹ + (1 - X)⁻¹ ^ 2 * ((1 - X)⁻¹ - ∑' k : ℕ+, X ^ (2 ^ (k : ℕ) + k - 1))

/--
**Conjecture (A006697)**: The generating function for the number of subwords of length $n$
in the infinite word generated by $a \mapsto aab, b \mapsto b$ is
$$\sum_{n \geq 0} a_n x^n = 1 + \frac{1}{1-x} + \frac{1}{(1-x)^2}\left(\frac{1}{1-x} -
  \sum_{k \geq 1} x^{2^k + k - 1}\right).$$
-/
@[category research open, AMS 68]
theorem conjecture : ∀ n, (a n : ℚ) = coeff ℚ n generatingFunction := by
  sorry

end OEIS.A006697
